name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: ./scripts/test_all.sh
      - name: Check no changes
        run: git diff-files -p --exit-code
